version: 2.1

#jobs:
  # job that creates infrastructure in AWS using cloud formation template and rollback on failure
  #create_infrastructure:
    #docker:
      #- image: amazon/aws-cli
    #steps:
      #- checkout
      #- run:
          #name: Ensure backend infrastructure exist
          #command: |
            #aws cloudformation deploy \
            #--template-file template.yml \
            #--stack-name my-stack \
            #--region us-west-2

jobs:
  # Exercise: Config and Deployment
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
            - "38:f8:c0:41:a0:62:4c:3a:88:9c:5e:14:4b:b3:a6:76"
      - run:
          name: "Install dependencies"
          command: |
            apk add --update ansible
      - run:
          name: "Configure server"
          command: |
            ansible-playbook -i inventory main.yml

workflows:
  my_workflow:
    jobs:
      #- create_infrastructure
      - configure_infrastructure
      
